name: Update Gacha Meta

on:
    workflow_dispatch: {}
    schedule:
        - cron: '0 12 * * *'

jobs:
    update:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Swift
              uses: swift-actions/setup-swift@v2

            - name: Update Gacha Meta Tag
              id: compare_shas
              run: |
                swift ./Script/UpdateGachaMetaDBSPM.swift

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v3
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                branch: update-assets-${{ github.run_number }}
                base: dev
                title: "Update Gacha Meta"
                body: |
                  This PR updates the GachaMetaDB SPM Tag.
                delete-branch: true
                assignees: ShikiSuen
                reviewers: ShikiSuen
                team-reviewers: |
                  owners
                  maintainers
