name: Update Assets

on:
    workflow_dispatch: {}
    schedule:
        - cron: '0 12 * * *'

jobs:
    update:
        runs-on: macOS-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Swift
              uses: swift-actions/setup-swift@v2

            - name: Pull and Compile Assets
              id: compare_shas
              run: |
                swift ./Script/RawAssetsPuller.swift
                zsh ./Script/convertAssetsToHEIC.sh
                swift ./Script/ImageAssetRegenerator.swift

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v3
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                branch: update-assets-${{ github.run_number }}
                base: dev
                title: "Update Assets"
                body: |
                  This PR updates the assets.
                delete-branch: true
                assignees: ShikiSuen
                reviewers: ShikiSuen
                team-reviewers: |
                  owners
                  maintainers
